### ISSUE TITLE
Idea: Add support for separate `allowfullscreen` attribute?

### ISSUE THREAD

**Issue by jimmywarting** [JamesMGreene/sandblaster#1]
Think fullscreen can be always detectable by using `document.fullscreenEnabled` {boolean}
(msFullscreenEnabled, mozFullScreenEnabled, webkitFullscreenEnabled)

**Comment by JamesMGreene** [comment]
Although I see where you're coming from, the `allowfullscreen` capability is technically outside of the scope of `iframe[sandbox]`, so I'm currently disinclined to pursue that one further.

However, if you have more explanation of why you think it might fit here, then I'm open to reconsidering. :+1:

**Comment by jimmywarting** [comment]
Sometimes it reports null (uncertain) If it can't Read the sandbox attribut.

Taking it from the enable flag will certain report back true or false

**Comment by JamesMGreene** [comment]
> Sometimes it reports null (uncertain) If it can't Read the sandbox attribut.

What does?  I'm not following you.

This library does not support the `allowfullscreen` attribute as that attribute is not a part of the `iframe` sandboxing (`sandbox` attribute) spec.

I can agree with you that `allowfullscreen` has some internal sandboxing implications on `iframe` elements but it is not a member token of the `sandbox` attribute. Because it is a separate attribute, it can also be used without other `iframe` sandboxing (via the `sandbox` attribute); the latter has huge effect on security and capabilities in the `iframe` element's `contentDocument`.

**Comment by JamesMGreene** [comment]
More information on the implementation of `allowfullscreen` being outside of the `sandbox`:
   https://lists.w3.org/Archives/Public/public-webapps/2012JulSep/0256.html

Click through the various replies using the "Next in thread" links.

**Comment by jimmywarting** [comment]
Oh, You are right. I totally forgot that full screen is not part of the sandbox. And it has it's own attribute. I have even used allowfullscreen attribute for youtube videos so i should know better :P<br> I didn't read the README.me clearly and i thought sandboxAllowances had fullscreen in there. My mistake. Was to long ago since I even used it

**Comment by JamesMGreene** [comment]
No worries! 😄
