### ISSUE TITLE
Not working in office365 integrations

### ISSUE THREAD

**Issue by pekhota** [JamesMGreene/sandblaster#3]
They are using the following code for iframe: 

``` html
<iframe id="some id" width="100%" height="100%" frameborder="0" title="PDFfiller"
        sandbox="allow-scripts allow-forms allow-same-origin ms-allow-popups allow-popups"
        name="" class="AddinIframe"></iframe>
```

You code showing nothing. Can u help me?

**Comment by JamesMGreene** [comment]
To be clear, are you using Sandblaster as a script within that `iframe`?  The intended usage is to detect the state of the current page (i.e. detect if the page including the Sandblaster code is _**within**_ an `iframe` that is sandboxed).

However, I suppose I could add support for passing in a `Window` object or an `iframe` element.  Is that what you are expecting?  I am unclear from your initial comment, so please explain a bit further.  Thanks!

**Comment by pekhota** [comment]
Steps to reproduce:
1. Open onedrive online. Use this link [https://onedrive.live.com/](https://onedrive.live.com/). Then find some docx document and try to edit it. It should looks something like this: http://joxi.ru/Ra2XDpZCMNJM2g
2. Then press the button to edit the document: http://joxi.ru/8ZrJ4DYCRav52j
3. Click 1 and then click 2: http://joxi.ru/BLmG4xeCKMvO2l
4. Find out in the store the app with the name PDFfiller http://joxi.ru/9E2pLo1HbKwL2Y
5. When you select pdffiller you will find the following window http://joxi.ru/1bmodpztkRwJ2y
6. Press Export to pdffiller. Then you will see new window: http://joxi.ru/gV2Vp1LcMwN3rv
7. Open console and insert your code there: http://joxi.ru/gkrD4NlCWRwPrp
8. What says your library: http://joxi.ru/NDrllnoi59QbrP
9. Proof that window is sandboxed: http://joxi.ru/j1A514xhv9EnAE

We have a lot of problems with that mode. So if you can resolve that problem, it would be great.

**Comment by JamesMGreene** [comment]
So, if you are opening the console and using Sandblaster in the new window that gets opened, that is not an `iframe`. At least as of now, that is all that Sandblaster is intended for: analyzing sandboxed `iframe` documents, _NOT_ analyzing sandboxed windows.  I'm not sure if that is even possible... but, if it is, I would be interested in adding support for such.  I also do not see that error message that you included in the screenshot of Step 9.

However, if you open the console and use Sandblaster to analyze your right-side "tab" within the Word document editing view (you'll have to select the appropriate window to target from the console, otherwise you'll be interacting with the `top` window), you will find that it is essentially hindered from detecting any specific allowance information as it is a cross-origin frame and therefore subject to the [same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy):

``` js
console.log( JSON.stringify( sandblaster.detect(), null, 2 ) );
```

**Result:**

``` json
{
  "framed": true,
  "crossOrigin": true,
  "sandboxed": null,
  "sandboxAllowances": {
    "forms": null,
    "modals": null,
    "orientationLock": null,
    "pointerLock": null,
    "popups": null,
    "popupsToEscapeSandbox": null,
    "sameOrigin": null,
    "scripts": true,
    "topNavigation": null
  },
  "unsandboxable": false,
  "resandboxable": false,
  "sandboxable": false,
  "errors": []
}
```

Sadly, I don't know of any way at the moment to give further analysis of your particular situation.  The browser spec requires them to be very restrictive of any cross-origin `iframe` scripting. 😞

**Comment by JamesMGreene** [comment]
Feel free to follow up if you have any other questions or suggestions.

**Comment by JamesMGreene** [comment]
For the record, some other values of note from within the `iframe`:

`window.location.href`:
`https://api.pdffiller.com/office/App/Home/Home.html?et=...`

`document.domain`:
`api.pdffiller.com`
